saintseiya_api/api/urls.py
from django.urls import path
from .views import *

app_name = 'API'
urlpatterns = [
    path('Athena/', AthenaViewSet.as_view(), name='AthenaViewSet'),
    path('AddSaint/', AthenaPostSaint.as_view(), name='AthenaPostSaint'),
]

saintseiya_api/saintseiya_api/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sanctuary.urls')),
    path('', include('api.urls'))
]

saintseiya_api/sanctuary/urls.py
from django.urls import path
from . import views
app_name = 'Athena'

urlpatterns = [
    path('', views.Index.as_view(), name='Index'),
    path('CreateAthenaSaint/', views.CreateAthenaSaint.as_view(), name='CreateAthenaSaint'),
    path('Apis/', views.All_Apis.as_view(), name='AllApis'),
    path('About/', views.About.as_view(), name='About'),
    path('Community/', views.Community.as_view(), name='help'),
]

saintseiya_api/api/models.py
from django.db import models

# Create your models here.

saintseiya_api/sanctuary/models.py
from django.db import models
from .Cloths import * 
# Create your models here.
class Saint(models.Model):
    name = models.CharField(max_length=20)
    cloth = models.CharField(max_length=30,choices=CLOTHS)
    date_birth = models.DateField()
    picture = models.ImageField(blank=True, upload_to='media')

saintseiya_api/sanctuary/forms.py
from django import forms
from .models import *

class SaintForm(forms.ModelForm):
    class Meta:
        model = Saint
        fields = '__all__'
        widgets = {
            'name' : forms.TextInput(attrs={'type' :"text", 'class' :"form-control", 'id' : "formGroupExampleInput", 'placeholder':"Name"}),
            'cloth' : forms.Select(),
            'date_birth' : forms.TextInput(attrs={'type' : 'date'}),
            'picture' : forms.FileInput(attrs={'type' : 'file', 'class' :"form-control",  'id' : "formFileMultiple"})
        }

  

saintseiya_api/api/views.py
from django.shortcuts import get_object_or_404
from  .serializer import *
from rest_framework.views import APIView
from rest_framework.response import Response
from sanctuary.models import *
from rest_framework import generics

# Create your views here.

class AthenaViewSet(APIView):
    def get(self, request, format=None):
        queryset = Saint.objects.all()
        serializer = AthenaSerializer(queryset, many=True)
        return Response(serializer.data)

class AthenaPostSaint(generics.CreateAPIView):
    serializer_class = AthenaSerializer
    queryset = Saint.objects.all()
    

saintseiya_api/sanctuary/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, FormView, CreateView
from .forms import *
from django.urls import reverse_lazy

# Create your views here.

class Index(TemplateView):
    template_name = 'index.html'

class CreateAthenaSaint(CreateView):
    template_name = 'Form.html'
    form_class = SaintForm
    success_url = reverse_lazy('Athena:CreateAthenaSaint')

class All_Apis(TemplateView):
    template_name = 'apis.html'

class About(TemplateView):
    template_name = 'about.html'

class Community(TemplateView):
    template_name = 'community.html'

saintseiya_api/templates/Form.html
{% extends 'apis.html' %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">
        Done
    </button>
</form>
{% endblock content %}

saintseiya_api/templates/about.html
{% extends 'apis.html' %}

{% block content %}
<p>
    Hey Guys!
    Nice to meet you, This is a Seint Seiya API, it's totally free,
    We're working to get better this API, of course we have to pay the server
    and production.
</p>
{% endblock content %}

saintseiya_api/templates/apis.html
{% load static %}
<html>
    <head>
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <link href="{% static 'apis.css' %}" rel="stylesheet" id="bootstrap-css">
        <!------ Include the above in your HEAD tag ---------->
    </head>

    <body>
        <div class="wrapper fadeInDown">
          
            <div id="formContent">
              <!-- Tabs Titles -->
          
              <!-- apis -->
              {% block content %}
              <P>
                <H3>API</H3>
                <a href="{% url 'API:AthenaViewSet' %}">    <label> Athena Saints </label>     </a>
                <br />
                <a href="{% url 'API:AthenaPostSaint' %}">    <label> Add Saints </label>     </a>
              </P>

              <!-- Remind Passowrd -->
              <div id="formFooter">
                <a href="{% url 'Athena:About' %}"  class="underlineHover" href="#">Learn more</a>
                <a href="{% url 'Athena:help' %}"  class="underlineHover" href="#">Community</a>
              </div>
              {% endblock content %}
            </div>
        </div>
    </body>
</html>

saintseiya_api/templates/community.html
<html>
    <head>
        <script>
            window.fbAsyncInit = function() {
              FB.init({
                appId            : 'your-app-id',
                autoLogAppEvents : true,
                xfbml            : true,
                version          : 'v9.0'
              });
            };
          </script>
          <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js"></script>          

    </head>
    <body>
        <div id="fb-root"></div>
        <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v9.0&appId=390393298573582&autoLogAppEvents=1" nonce="j5J4dWvO"></script>
        <div class="fb-comments" data-href="http://localhost:8000/Community/" data-width="" data-numposts="10"></div>
    </body>
</html>

saintseiya_api/templates/index.html
{% load static %}
<html>
    <head>
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
        <!-- JavaScript Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
        <title>Seint Seiya API</title>
    </head>
    <body>
      
        <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
          
            <ol class="carousel-indicators">
              <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"></li>
              <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"></li>
              <li data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"></li>
            </ol>

            
            <div class="carousel-inner">
              <div class="carousel-item active">
                
                
                <img src="{% static 'Galery/2.jpg' %}" class="d-block w-100" >
                <div class="carousel-caption d-none d-md-block">
                  <a href="{% url 'Athena:AllApis' %}">  <button type="button" class="btn btn-primary" > API </button> </a>
                  <a href="{% url 'Athena:CreateAthenaSaint' %}">  <button type="button" class="btn btn-primary" > Add Saint</button> </a> 
                </div>
                
              </div>
              <div class="carousel-item">
                <img src="{% static 'Galery/1.png' %}" class="d-block w-1000" height="100%">
                <div class="carousel-caption d-none d-md-block">
                  <a href="{% url 'Athena:About' %}">  <button type="button" class="btn btn-primary" > API </button> </a> 
                </div>
              </div>
              <div class="carousel-item">
                <img src="{% static 'Galery/3.jpg' %}" class="d-block w-100">
                <div class="carousel-caption d-none d-md-block">
                  <a href="{% url 'Athena:About' %}">  <button type="button" class="btn btn-primary" > API </button> </a> 
                </div>
              </div>
            </div>
            
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </a>
            
          
          </div>
      
    </body>

</html>





       